/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptPendingInvites200JoinedItem } from './acceptPendingInvites200JoinedItem.js';

export type AcceptPendingInvites200 = {
  joined: AcceptPendingInvites200JoinedItem[];
};
