/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AddOrgEmailDomainBody = {
  /**
     * @minLength 1
     * @maxLength 253
     * @pattern ^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$
     */
  domain: string;
};
