/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentModelSupportResponseAgents = {[key: string]: {
  status: 'available';
  /** @minLength 1 */
  agentType: string;
  /** @minLength 1 */
  displayName: string;
  providers: ({
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  displayName: string;
  description?: string;
  keyTypes?: ('apiKey' | 'subscription')[];
  modelProvider?: 'anthropic' | 'openai' | 'xai' | 'google' | 'openrouter' | 'cursor' | 'fireworks-ai' | 'vercel' | 'nebius';
})[];
  endpoints: ({
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  displayName: string;
  description?: string;
  envVars: {
  /** @minLength 1 */
  name: string;
  required: boolean;
  fromSecret: boolean;
  description?: string;
}[];
  availability: {
  available: boolean;
  reasons: ('credential_status_unknown' | 'missing_required_env_var' | 'matrix_unavailable')[];
  missingEnvVars: string[];
};
})[];
  providerEndpoints: {
  /** @minLength 1 */
  providerId: string;
  /** @minLength 1 */
  modelEndpointId: string;
}[];
  /** @minLength 1 */
  defaultEndpoint: string;
  defaultProvider?: string;
  defaultModel?: string;
  defaultSource?: 'admin' | 'system_recommended' | 'fallback';
  discovery: {
  method: 'static';
};
  discoveredModels?: {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  displayName: string;
  /** @minLength 1 */
  providerId: string;
}[];
  discoveryStatus?: 'ready' | 'pending';
} | {
  status: 'unavailable';
  /** @minLength 1 */
  agentType: string;
  reason: 'matrix_unavailable' | 'unsupported_schema_version' | 'invalid_matrix';
  /** @minLength 1 */
  message: string;
}};
