/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentAssociationRole = typeof AgentAssociationRole[keyof typeof AgentAssociationRole];


export const AgentAssociationRole = {
  creator: 'creator',
  reviewer: 'reviewer',
  assignee: 'assignee',
} as const;
