/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AgentModelSupportResponseAgents } from './agentModelSupportResponseAgents.js';
import type { AgentModelSupportResponseDefaultAgentTypeSource } from './agentModelSupportResponseDefaultAgentTypeSource.js';
import type { AgentModelSupportResponseLaunchableAgentsItem } from './agentModelSupportResponseLaunchableAgentsItem.js';

export interface AgentModelSupportResponse {
  agents: AgentModelSupportResponseAgents;
  defaultAgentType?: string;
  defaultAgentTypeSource?: AgentModelSupportResponseDefaultAgentTypeSource;
  launchableAgents?: AgentModelSupportResponseLaunchableAgentsItem[];
}
