/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentModelSupportResponseLaunchableAgentsItem = {
  /** @minLength 1 */
  agentType: string;
  /** @minLength 1 */
  displayName: string;
  multiModel: boolean;
  enabled: boolean;
};
