/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentAttachments = {
  attachmentId: string;
  pluginName: string;
  config?: unknown;
}[] | null;
