/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AgentServiceStatus } from './agentServiceStatus.js';

export interface AgentServiceStatusesResponse {
  services: AgentServiceStatus[];
}
