/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentSandboxOptionsCustomSize = {
  /**
     * @minLength 1
     * @maxLength 50
     */
  name: string;
  /** @minimum 0.5 */
  cpuCores: number;
  /**
     * @minimum 1
     * @maximum 9007199254740991
     */
  gbMemory: number;
  diskSizeGb?: number | null;
} | null;
