/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentLabelSource = typeof AgentLabelSource[keyof typeof AgentLabelSource];


export const AgentLabelSource = {
  builtin: 'builtin',
  user: 'user',
  generated: 'generated',
} as const;
