/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export interface AgentServiceStatus {
  id: string;
  label?: string;
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  port?: number;
  status: string;
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  pid?: number;
  running?: boolean;
}
