/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentSandboxOptionsResourceSize = typeof AgentSandboxOptionsResourceSize[keyof typeof AgentSandboxOptionsResourceSize] | null;


export const AgentSandboxOptionsResourceSize = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  X_LARGE: 'X_LARGE',
  XX_LARGE: 'XX_LARGE',
} as const;
