/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AgentModelSupportResponseDefaultAgentTypeSource = typeof AgentModelSupportResponseDefaultAgentTypeSource[keyof typeof AgentModelSupportResponseDefaultAgentTypeSource];


export const AgentModelSupportResponseDefaultAgentTypeSource = {
  admin: 'admin',
  system_fallback: 'system_fallback',
} as const;
