/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type ArchiveAllAgents200 = {
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  archived: number;
};
