/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type ArchiveAllAgentsBody = {
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  createdAtFrom?: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  createdAtTo?: number;
  userId?: string;
};
