/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AvailableSecretCategory = typeof AvailableSecretCategory[keyof typeof AvailableSecretCategory];


export const AvailableSecretCategory = {
  integration: 'integration',
  custom: 'custom',
  user: 'user',
  team: 'team',
} as const;
