/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type AxonEventOrigin = typeof AxonEventOrigin[keyof typeof AxonEventOrigin];


export const AxonEventOrigin = {
  EXTERNAL_EVENT: 'EXTERNAL_EVENT',
  AGENT_EVENT: 'AGENT_EVENT',
  USER_EVENT: 'USER_EVENT',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
} as const;
