/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AxonEventOrigin } from './axonEventOrigin.js';
import type { AxonEventType } from './axonEventType.js';

export interface AxonEvent {
  id: string;
  sequence?: number;
  streamId: string;
  type: AxonEventType;
  payload: unknown;
  timestamp: number;
  origin?: AxonEventOrigin;
  source?: string;
}
