/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type BaseImageViewArchitecture = typeof BaseImageViewArchitecture[keyof typeof BaseImageViewArchitecture];


export const BaseImageViewArchitecture = {
  x86_64: 'x86_64',
  arm64: 'arm64',
} as const;
