/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { BlueprintArchitecture } from './blueprintArchitecture.js';
import type { BlueprintBuildArgs } from './blueprintBuildArgs.js';
import type { BlueprintBuildSecretsItem } from './blueprintBuildSecretsItem.js';
import type { BlueprintCustomSize } from './blueprintCustomSize.js';
import type { BlueprintFileMounts } from './blueprintFileMounts.js';
import type { BlueprintMetadata } from './blueprintMetadata.js';
import type { BlueprintResourceSize } from './blueprintResourceSize.js';
import type { BlueprintStatus } from './blueprintStatus.js';

export interface Blueprint {
  id: string;
  name: string;
  status: BlueprintStatus;
  createTimeMs: number;
  buildFinishTimeMs?: number;
  metadata?: BlueprintMetadata;
  failureReason?: string;
  dockerfile?: string;
  resourceSize?: BlueprintResourceSize;
  customSize?: BlueprintCustomSize;
  systemSetupCommands?: string[];
  launchCommands?: string[];
  baseBlueprintName?: string;
  fileMounts?: BlueprintFileMounts;
  installCommand?: string;
  repoBranch?: string;
  buildArgs?: BlueprintBuildArgs;
  buildSecrets?: BlueprintBuildSecretsItem[];
  architecture?: BlueprintArchitecture;
}
