/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type BlueprintStatus = typeof BlueprintStatus[keyof typeof BlueprintStatus];


export const BlueprintStatus = {
  queued: 'queued',
  provisioning: 'provisioning',
  building: 'building',
  failed: 'failed',
  build_complete: 'build_complete',
} as const;
