/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type BlueprintBuildSecretsItem = {
  /**
     * @minLength 1
     * @pattern ^[A-Z][A-Z0-9_]*$
     */
  envVar: string;
  /** @minLength 1 */
  secretRef: string;
};
