/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateBlueprintBodyResourceSize = typeof CreateBlueprintBodyResourceSize[keyof typeof CreateBlueprintBodyResourceSize];


export const CreateBlueprintBodyResourceSize = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  X_LARGE: 'X_LARGE',
  XX_LARGE: 'XX_LARGE',
} as const;
