/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateServiceAccount201ServiceAccountStatus = typeof CreateServiceAccount201ServiceAccountStatus[keyof typeof CreateServiceAccount201ServiceAccountStatus];


export const CreateServiceAccount201ServiceAccountStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;
