/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateServiceAccountBody = {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  /** @minLength 1 */
  roleId: string;
};
