/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMyModelProviderSecretBodyProvider } from './createMyModelProviderSecretBodyProvider.js';
import type { CreateMyModelProviderSecretBodyType } from './createMyModelProviderSecretBodyType.js';

export type CreateMyModelProviderSecretBody = {
  provider: CreateMyModelProviderSecretBodyProvider;
  type: CreateMyModelProviderSecretBodyType;
  /**
     * @minLength 1
     * @maxLength 64
     * @pattern ^[a-zA-Z0-9_-]+$
     */
  name: string;
  /** @minLength 1 */
  value: string;
  baseUrl?: string | null;
};
