/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationBodyOrgOnboardingProfile } from './createOrganizationBodyOrgOnboardingProfile.js';

export type CreateOrganizationBody = {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 60
     */
  slug?: string;
  avatarUrl?: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  supportEmail?: string;
  /**
     * @items.minLength 1
     * @items.maxLength 253
     * @items.pattern ^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$
     */
  emailDomains?: string[];
  pluginNames?: string[];
  orgOnboardingProfile?: CreateOrganizationBodyOrgOnboardingProfile;
};
