/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateAgentResponseStatus = typeof CreateAgentResponseStatus[keyof typeof CreateAgentResponseStatus];


export const CreateAgentResponseStatus = {
  starting: 'starting',
  running: 'running',
  needs_input: 'needs_input',
  completed: 'completed',
  interrupted: 'interrupted',
  stopping: 'stopping',
  stopped: 'stopped',
  error: 'error',
  terminated: 'terminated',
} as const;
