/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBlueprintBodyArchitecture } from './createBlueprintBodyArchitecture.js';
import type { CreateBlueprintBodyBuildArgs } from './createBlueprintBodyBuildArgs.js';
import type { CreateBlueprintBodyBuildSecretsItem } from './createBlueprintBodyBuildSecretsItem.js';
import type { CreateBlueprintBodyCustomSize } from './createBlueprintBodyCustomSize.js';
import type { CreateBlueprintBodyFileMounts } from './createBlueprintBodyFileMounts.js';
import type { CreateBlueprintBodyRepoAccess } from './createBlueprintBodyRepoAccess.js';
import type { CreateBlueprintBodyResourceSize } from './createBlueprintBodyResourceSize.js';
import type { CreateBlueprintBodyUserMode } from './createBlueprintBodyUserMode.js';

export type CreateBlueprintBody = {
  /** @minLength 1 */
  name: string;
  dockerfile: string;
  userMode: CreateBlueprintBodyUserMode;
  resourceSize?: CreateBlueprintBodyResourceSize;
  customSize?: CreateBlueprintBodyCustomSize;
  repoSlug?: string;
  repoAccess?: CreateBlueprintBodyRepoAccess;
  repoBranch?: string;
  installCommand?: string;
  systemSetupCommands?: string[];
  launchCommands?: string[];
  baseBlueprintName?: string;
  fileMounts?: CreateBlueprintBodyFileMounts;
  buildArgs?: CreateBlueprintBodyBuildArgs;
  buildSecrets?: CreateBlueprintBodyBuildSecretsItem[];
  isBase?: boolean;
  architecture?: CreateBlueprintBodyArchitecture;
};
