/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateTeamModelProviderSecretBodyType = typeof CreateTeamModelProviderSecretBodyType[keyof typeof CreateTeamModelProviderSecretBodyType];


export const CreateTeamModelProviderSecretBodyType = {
  apiKey: 'apiKey',
  subscription: 'subscription',
} as const;
