/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateAgentBodyPromptMode = typeof CreateAgentBodyPromptMode[keyof typeof CreateAgentBodyPromptMode];


export const CreateAgentBodyPromptMode = {
  implement: 'implement',
  plan: 'plan',
} as const;
