/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateMyModelProviderSecretBodyProvider = typeof CreateMyModelProviderSecretBodyProvider[keyof typeof CreateMyModelProviderSecretBodyProvider];


export const CreateMyModelProviderSecretBodyProvider = {
  anthropic: 'anthropic',
  openai: 'openai',
  xai: 'xai',
  google: 'google',
  openrouter: 'openrouter',
  cursor: 'cursor',
  'fireworks-ai': 'fireworks-ai',
  vercel: 'vercel',
  nebius: 'nebius',
} as const;
