/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateServiceAccount201ServiceAccount } from './createServiceAccount201ServiceAccount.js';

export type CreateServiceAccount201 = {
  serviceAccount: CreateServiceAccount201ServiceAccount;
};
