/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAgentResponseSandboxOptionsCustomSize } from './createAgentResponseSandboxOptionsCustomSize.js';
import type { CreateAgentResponseSandboxOptionsResourceSize } from './createAgentResponseSandboxOptionsResourceSize.js';

export type CreateAgentResponseSandboxOptions = {
  blueprintName?: string | null;
  blueprintId?: string | null;
  snapshotId?: string | null;
  resourceSize?: CreateAgentResponseSandboxOptionsResourceSize;
  customSize?: CreateAgentResponseSandboxOptionsCustomSize;
  dockerd?: boolean | null;
  computerUse?: boolean | null;
  artifactMirrors?: boolean | null;
  idleTimeMinutes?: number | null;
  resumeOnHttp?: boolean | null;
} | null;
