/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AgentAssociation } from './agentAssociation.js';
import type { CreateAgentResponseAttachments } from './createAgentResponseAttachments.js';
import type { CreateAgentResponseDaemons } from './createAgentResponseDaemons.js';
import type { CreateAgentResponseEnvVars } from './createAgentResponseEnvVars.js';
import type { CreateAgentResponseSandboxOptions } from './createAgentResponseSandboxOptions.js';
import type { CreateAgentResponseStatus } from './createAgentResponseStatus.js';

export interface CreateAgentResponse {
  id: string;
  streamId: string;
  agentType: string;
  status: CreateAgentResponseStatus;
  devboxId: string | null;
  tunnelKey?: string | null;
  name: string;
  prompt: string;
  systemPrompt?: string | null;
  model?: string | null;
  blueprintId?: string | null;
  blueprintName?: string | null;
  sandboxOptions?: CreateAgentResponseSandboxOptions;
  createdAt: number;
  lastActiveAt?: number | null;
  archived: boolean;
  userId?: string | null;
  prUrl?: string | null;
  associations?: AgentAssociation[] | null;
  daemons?: CreateAgentResponseDaemons;
  attachments?: CreateAgentResponseAttachments;
  envVars?: CreateAgentResponseEnvVars;
  organizationId: string;
  modelProviderSecretId?: string | null;
  credentialSyncPending?: boolean | null;
  originator?: string | null;
  pinned: boolean;
  launchWarnings?: string[];
}
