/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateBlueprintBodyUserMode = typeof CreateBlueprintBodyUserMode[keyof typeof CreateBlueprintBodyUserMode];


export const CreateBlueprintBodyUserMode = {
  root: 'root',
  user: 'user',
} as const;
