/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type CreateAgentResponseMark = typeof CreateAgentResponseMark[keyof typeof CreateAgentResponseMark] | null;


export const CreateAgentResponseMark = {
  blocked: 'blocked',
  in_review: 'in_review',
  completed: 'completed',
} as const;
