/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePersonalApiKey201Key } from './createPersonalApiKey201Key.js';

export type CreatePersonalApiKey201 = {
  key: CreatePersonalApiKey201Key;
  token: string;
};
