/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAgentLabelRequest {
  /**
     * @minLength 1
     * @maxLength 40
     */
  name: string;
  /** @maxLength 200 */
  description?: string;
  agentIds?: string[];
}
