/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export interface CustomSandboxSizeLimits {
  /** @exclusiveMinimum 0 */
  maxCpuCores: number;
  /** @exclusiveMinimum 0 */
  maxGbMemory: number;
  /** @exclusiveMinimum 0 */
  maxDiskSizeGb: number;
}
