/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user.js';

export type DevLogin200 = {
  token: string;
  user: User;
};
