/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { EnqueueAgentMessageBodyAttachmentsItemType } from './enqueueAgentMessageBodyAttachmentsItemType.js';

export type EnqueueAgentMessageBodyAttachmentsItem = {
  id: string;
  type: EnqueueAgentMessageBodyAttachmentsItemType;
  name: string;
  url?: string;
  path?: string;
  mimeType?: string;
  size?: number;
  storageObjectId?: string;
  data?: string;
};
