/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type EnqueueAgentMessage201Attachments = ({
  id: string;
  type: 'file' | 'image' | 'link';
  name: string;
  url?: string;
  path?: string;
  mimeType?: string;
  size?: number;
  storageObjectId?: string;
  data?: string;
})[] | null;
