/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type FeatureFlagScope = typeof FeatureFlagScope[keyof typeof FeatureFlagScope];


export const FeatureFlagScope = {
  global: 'global',
  account: 'account',
} as const;
