/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type GetAuthStatus200MembershipsItemTeamsItem = {
  id: string;
  organizationId: string;
  slug: string;
  name: string;
  description: string | null;
  defaultRoleId?: string | null;
  createdAt: number;
};
