/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthStatus200MembershipsItemRolesItem } from './getAuthStatus200MembershipsItemRolesItem.js';
import type { GetAuthStatus200MembershipsItemTeamsItem } from './getAuthStatus200MembershipsItemTeamsItem.js';
import type { Organization } from './organization.js';

export type GetAuthStatus200MembershipsItem = {
  memberId: string;
  organization: Organization;
  roles: GetAuthStatus200MembershipsItemRolesItem[];
  /** @items.pattern ^[a-z_]+:[a-z_]+$ */
  permissions: string[];
  teams: GetAuthStatus200MembershipsItemTeamsItem[];
};
