/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAgentQueue200ItemAttachments } from './getAgentQueue200ItemAttachments.js';

export type GetAgentQueue200Item = {
  id: string;
  agentId: string;
  text: string;
  attachments: GetAgentQueue200ItemAttachments;
  position: number;
  userId: string | null;
  createdAt: number;
};
