/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type GetAuthSettings200Mode = typeof GetAuthSettings200Mode[keyof typeof GetAuthSettings200Mode];


export const GetAuthSettings200Mode = {
  off: 'off',
  allow: 'allow',
  deny: 'deny',
} as const;
