/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthSettings200Mode } from './getAuthSettings200Mode.js';

export type GetAuthSettings200 = {
  allowedEmailDomains: unknown[];
  allowedEmails: unknown[];
  mode: GetAuthSettings200Mode;
  allowSelfServeOrgCreation: boolean;
  updatedAt: number;
  updatedBy: string | null;
};
