/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBlueprintLogs200LogsItem } from './getBlueprintLogs200LogsItem.js';

export type GetBlueprintLogs200 = {
  logs: GetBlueprintLogs200LogsItem[];
};
