/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { TaggedActivityEvent } from './taggedActivityEvent.js';

export type GetRecentActivity200 = {
  items: TaggedActivityEvent[];
};
