/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type ListOrgModelProviderSecretDependents200DependentsItem = {
  kind: string;
  id: string;
  label: string;
};
