/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ModelProviderSecret } from './modelProviderSecret.js';

export type ListAccessibleModelProviderSecrets200 = {
  secrets: ModelProviderSecret[];
};
