/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AvailableSecret } from './availableSecret.js';

export type ListAvailableSecrets200 = {
  secrets: AvailableSecret[];
};
