/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPersonalApiKeys200KeysItem } from './listPersonalApiKeys200KeysItem.js';

export type ListPersonalApiKeys200 = {
  keys: ListPersonalApiKeys200KeysItem[];
};
