/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListOrganizationsResponseOrganizationsItemRolesItem } from './listOrganizationsResponseOrganizationsItemRolesItem.js';
import type { ListOrganizationsResponseOrganizationsItemTeamsItem } from './listOrganizationsResponseOrganizationsItemTeamsItem.js';
import type { Organization } from './organization.js';

export type ListOrganizationsResponseOrganizationsItem = {
  memberId: string;
  organization: Organization;
  roles: ListOrganizationsResponseOrganizationsItemRolesItem[];
  /** @items.pattern ^[a-z_]+:[a-z_]+$ */
  permissions: string[];
  teams: ListOrganizationsResponseOrganizationsItemTeamsItem[];
};
