/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListServiceAccounts200ServiceAccountsItem } from './listServiceAccounts200ServiceAccountsItem.js';

export type ListServiceAccounts200 = {
  serviceAccounts: ListServiceAccounts200ServiceAccountsItem[];
};
