/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type ListPendingInvites200InvitesItem = {
  inviteId: string;
  organizationId: string;
  organizationName: string;
  organizationSlug: string;
  organizationAvatarUrl: string | null;
  expiresAt: number;
};
