/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListOrganizationsResponseOrganizationsItemRolesItemScope } from './listOrganizationsResponseOrganizationsItemRolesItemScope.js';

export type ListOrganizationsResponseOrganizationsItemRolesItem = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  scope: ListOrganizationsResponseOrganizationsItemRolesItemScope;
  isBuiltin: boolean;
  /** @items.pattern ^[a-z_]+:[a-z_]+$ */
  permissions: string[];
};
