/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPendingInvites200InvitesItem } from './listPendingInvites200InvitesItem.js';

export type ListPendingInvites200 = {
  invites: ListPendingInvites200InvitesItem[];
};
