/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ScopedSecret } from './scopedSecret.js';

export type ListMySecrets200 = {
  secrets: ScopedSecret[];
};
