/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListServiceAccountApiKeys200KeysItem } from './listServiceAccountApiKeys200KeysItem.js';

export type ListServiceAccountApiKeys200 = {
  keys: ListServiceAccountApiKeys200KeysItem[];
};
