/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ListMcpTools200ToolsItemInputSchema } from './listMcpTools200ToolsItemInputSchema.js';

export type ListMcpTools200ToolsItem = {
  name: string;
  title?: string;
  description?: string;
  readOnly?: boolean;
  inputSchema?: ListMcpTools200ToolsItemInputSchema;
};
