/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type ModelProviderSecretType = typeof ModelProviderSecretType[keyof typeof ModelProviderSecretType];


export const ModelProviderSecretType = {
  apiKey: 'apiKey',
  subscription: 'subscription',
} as const;
