/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ModelProviderSecretProvider } from './modelProviderSecretProvider.js';
import type { ModelProviderSecretScope } from './modelProviderSecretScope.js';
import type { ModelProviderSecretType } from './modelProviderSecretType.js';

export interface ModelProviderSecret {
  /** @pattern ^mps_[A-Za-z0-9]{22}$ */
  id: string;
  organizationId: string;
  ownerId: string | null;
  scope: ModelProviderSecretScope;
  provider: ModelProviderSecretProvider;
  type: ModelProviderSecretType;
  /**
     * @minLength 1
     * @maxLength 96
     */
  name: string;
  /** @pattern ^sec_[A-Za-z0-9]{22}$ */
  secretId: string;
  tokenExpiresAt: number | null;
  baseUrl: string | null;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  createdAt: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  updatedAt: number;
}
