/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationDisabledReason = typeof OrganizationDisabledReason[keyof typeof OrganizationDisabledReason] | null;


export const OrganizationDisabledReason = {
  manual: 'manual',
  subscription_expired: 'subscription_expired',
  nonpayment: 'nonpayment',
} as const;
