/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationSubscriptionType } from './organizationSubscriptionType.js';

export type OrganizationSubscription = {
  type: OrganizationSubscriptionType;
  startsAt: number;
  endsAt: number;
} | null;
