/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationEnabledReleaseChannelsItem = typeof OrganizationEnabledReleaseChannelsItem[keyof typeof OrganizationEnabledReleaseChannelsItem];


export const OrganizationEnabledReleaseChannelsItem = {
  preview: 'preview',
  alpha: 'alpha',
  beta: 'beta',
} as const;
