/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ProvisionOrganizationRunloopAccount200Account } from './provisionOrganizationRunloopAccount200Account.js';

export type ProvisionOrganizationRunloopAccount200 = {
  ok: true;
  account: ProvisionOrganizationRunloopAccount200Account;
  pinnedAccountId: string;
};
