/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { CustomSandboxSizeLimits } from './customSandboxSizeLimits.js';
import type { MaintenanceState } from './maintenanceState.js';

export interface PublicConfig {
  tunnelDomain: string;
  platformUrl: string;
  githubWebBaseUrl: string;
  customSandboxSizeLimits?: CustomSandboxSizeLimits;
  maintenance: MaintenanceState;
}
