/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterCodexSubscriptionCredentialBodyBlob } from './registerCodexSubscriptionCredentialBodyBlob.js';

export type RegisterCodexSubscriptionCredentialBody = {
  blob: RegisterCodexSubscriptionCredentialBodyBlob;
  /**
     * @minLength 1
     * @maxLength 64
     * @pattern ^[a-zA-Z0-9_-]+$
     */
  alias?: string;
};
