/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type RegisterClaudeMaxCredentialBodyBlobClaudeAiOauth = {
  /** @minLength 1 */
  accessToken: string;
  /** @minLength 1 */
  refreshToken: string;
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  expiresAt: number;
  scopes: string[];
  subscriptionType?: string;
  rateLimitTier?: string;
};
