/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { ReorderAgentQueue200ItemAttachments } from './reorderAgentQueue200ItemAttachments.js';

export type ReorderAgentQueue200Item = {
  id: string;
  agentId: string;
  text: string;
  attachments: ReorderAgentQueue200ItemAttachments;
  position: number;
  userId: string | null;
  createdAt: number;
};
