/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SaveAgentDraftBodyPayloadEnvVarsItem = {
  /**
     * @minLength 1
     * @pattern ^[A-Za-z_][A-Za-z0-9_]*$
     */
  key: string;
  value?: string;
  secretRef?: string;
  isSecret?: boolean;
};
