/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SaveAgentDraftBodyPayloadPromptMode = typeof SaveAgentDraftBodyPayloadPromptMode[keyof typeof SaveAgentDraftBodyPayloadPromptMode];


export const SaveAgentDraftBodyPayloadPromptMode = {
  implement: 'implement',
  plan: 'plan',
} as const;
