/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SaveAgentDraftBodyPayloadAuthMethod = typeof SaveAgentDraftBodyPayloadAuthMethod[keyof typeof SaveAgentDraftBodyPayloadAuthMethod];


export const SaveAgentDraftBodyPayloadAuthMethod = {
  'org-key': 'org-key',
  'claude-max': 'claude-max',
  'codex-subscription': 'codex-subscription',
} as const;
