/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SaveAgentDraftBodyPayloadContentItem = {
  type: 'text';
  text: string;
} | {
  type: 'image';
  mimeType: string;
  data: string;
} | {
  type: 'file';
  name: string;
  mimeType: string;
  data: string;
};
