/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export interface ScopedSecret {
  /** @pattern ^sec_[A-Za-z0-9]{22}$ */
  id: string;
  /**
     * @minLength 1
     * @maxLength 64
     * @pattern ^[A-Z][A-Z0-9_]*$
     */
  name: string;
  ownerId: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  createdAt: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  updatedAt: number;
}
