/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SetAgentMarkBodyMark = typeof SetAgentMarkBodyMark[keyof typeof SetAgentMarkBodyMark] | null;


export const SetAgentMarkBodyMark = {
  blocked: 'blocked',
  in_review: 'in_review',
  completed: 'completed',
} as const;
