/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SetAccountFeatureFlag200Item = {
  key: string;
  label: string;
  description: string;
  enabled: boolean;
  defaultValue: boolean;
  hasOverride: boolean;
};
