/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { SetAgentMarkBodyMark } from './setAgentMarkBodyMark.js';

export type SetAgentMarkBody = {
  mark: SetAgentMarkBodyMark;
};
