/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { Snapshot } from './snapshot.js';
import type { SnapshotStatusResponseStatus } from './snapshotStatusResponseStatus.js';

export interface SnapshotStatusResponse {
  status: SnapshotStatusResponseStatus;
  errorMessage?: string;
  snapshot?: Snapshot;
}
