/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type SnapshotStatusResponseStatus = typeof SnapshotStatusResponseStatus[keyof typeof SnapshotStatusResponseStatus];


export const SnapshotStatusResponseStatus = {
  in_progress: 'in_progress',
  error: 'error',
  complete: 'complete',
  deleted: 'deleted',
} as const;
