/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type StartDeviceAuthBody = {
  /**
     * @minLength 1
     * @maxLength 255
     */
  hostname?: string;
  /**
     * @minLength 1
     * @maxLength 80
     */
  clientName?: string;
};
