/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { AxonEvent } from './axonEvent.js';

export interface TaggedActivityEvent {
  event: AxonEvent;
  agentId: string;
  agentName: string;
}
