/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateQueuedAgentMessage200Attachments } from './updateQueuedAgentMessage200Attachments.js';

export type UpdateQueuedAgentMessage200 = {
  id: string;
  agentId: string;
  text: string;
  attachments: UpdateQueuedAgentMessage200Attachments;
  position: number;
  userId: string | null;
  createdAt: number;
};
