/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrgRoleBody = {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name?: string;
  description?: string | null;
  /** @items.pattern ^[a-z_]+:[a-z_]+$ */
  permissions?: string[];
};
