/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrganizationBodyEnabledReleaseChannelsItem = typeof UpdateOrganizationBodyEnabledReleaseChannelsItem[keyof typeof UpdateOrganizationBodyEnabledReleaseChannelsItem];


export const UpdateOrganizationBodyEnabledReleaseChannelsItem = {
  preview: 'preview',
  alpha: 'alpha',
  beta: 'beta',
} as const;
