/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateQueuedAgentMessageBodyAttachmentsItemType = typeof UpdateQueuedAgentMessageBodyAttachmentsItemType[keyof typeof UpdateQueuedAgentMessageBodyAttachmentsItemType];


export const UpdateQueuedAgentMessageBodyAttachmentsItemType = {
  file: 'file',
  image: 'image',
  link: 'link',
} as const;
