/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAuthSettings200Mode } from './updateAuthSettings200Mode.js';

export type UpdateAuthSettings200 = {
  allowedEmailDomains: unknown[];
  allowedEmails: unknown[];
  mode: UpdateAuthSettings200Mode;
  allowSelfServeOrgCreation: boolean;
  updatedAt: number;
  updatedBy: string | null;
};
