/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import type { UpsertLlmTaskAssignmentBodyModel } from './upsertLlmTaskAssignmentBodyModel.js';

export type UpsertLlmTaskAssignmentBody = {
  enabled: boolean;
  model?: UpsertLlmTaskAssignmentBodyModel;
  providerSecretId?: string | null;
};
