/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Reflex API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListAgentAssociationsParams
} from './model/listAgentAssociationsParams.js';

import { apiFetch } from '../react-mutator.js';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List agent work-item associations in the active organization.
 */
export const listAgentAssociations = (
    params?: ListAgentAssociationsParams,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {


      return apiFetch<void>(
      {url: `/agent-associations`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListAgentAssociationsQueryKey = (params?: ListAgentAssociationsParams,) => {
    return [
    `/agent-associations`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAgentAssociationsQueryOptions = <TData = Awaited<ReturnType<typeof listAgentAssociations>>, TError = unknown>(params?: ListAgentAssociationsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAgentAssociations>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAgentAssociationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAgentAssociations>>> = ({ signal }) => listAgentAssociations(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAgentAssociations>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAgentAssociationsQueryResult = NonNullable<Awaited<ReturnType<typeof listAgentAssociations>>>
export type ListAgentAssociationsQueryError = unknown


/**
 * @summary List agent work-item associations in the active organization.
 */

export function useListAgentAssociations<TData = Awaited<ReturnType<typeof listAgentAssociations>>, TError = unknown>(
 params?: ListAgentAssociationsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAgentAssociations>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAgentAssociationsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






