#!/usr/bin/env node
/**
 * Emit `src/generated/api-ops.ts` from the committed public OpenAPI spec.
 *
 * The output is pure data: one record per operation with its method, path
 * template, parameter split, and summary. The `reflex api` command dispatches
 * these records through `reflexRequest` at runtime, so every public
 * operation is callable without a hand-written command. Regenerate with
 * `pnpm --filter @runloop/reflex-cli generate:api-ops` (or `pnpm api:generate` at the
 * repo root); `pnpm --filter @runloop/reflex-cli test` fails on drift.
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, '../../..', 'openapi', 'openapi.public.json');
const outPath = resolve(here, '..', 'src', 'generated', 'api-ops.ts');

export function buildApiOps(spec) {
  const ops = [];
  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      if (typeof op !== 'object' || op === null || !op.operationId) continue;
      const params = Array.isArray(op.parameters) ? op.parameters : [];
      // Path params in path-template order, so positional CLI args line up
      // with the URL left to right regardless of declaration order.
      const inPath = new Set(params.filter((p) => p.in === 'path').map((p) => p.name));
      const pathParams = [...path.matchAll(/\{([^}]+)\}/g)]
        .map((m) => m[1])
        .filter((name) => inPath.has(name) || true);
      const query = params
        .filter((p) => p.in === 'query')
        .map((p) => ({ name: p.name, required: Boolean(p.required) }));
      ops.push({
        id: op.operationId,
        method: method.toUpperCase(),
        path,
        ...(op.summary ? { summary: op.summary } : {}),
        pathParams,
        queryParams: query,
        hasBody: Boolean(op.requestBody),
      });
    }
  }
  ops.sort((a, b) => a.id.localeCompare(b.id));
  return ops;
}

export function renderModule(ops) {
  const lines = [
    '// Generated by scripts/generate-api-ops.mjs from openapi/openapi.public.json.',
    '// Do not edit manually; regenerate with `pnpm --filter @runloop/reflex-cli generate:api-ops`.',
    '',
    'export interface ApiOp {',
    '  id: string;',
    '  method: string;',
    '  /** OpenAPI path template, `{param}` style, relative to /api. */',
    '  path: string;',
    '  summary?: string;',
    '  /** Path params in template order; filled from positional CLI args. */',
    '  pathParams: string[];',
    '  queryParams: { name: string; required: boolean }[];',
    '  hasBody: boolean;',
    '}',
    '',
    `export const API_OPS: readonly ApiOp[] = ${JSON.stringify(ops, null, 2)};`,
    '',
  ];
  return lines.join('\n');
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const spec = JSON.parse(readFileSync(specPath, 'utf8'));
  const ops = buildApiOps(spec);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderModule(ops), 'utf8');
  console.log(`[reflex-cli] wrote ${ops.length} operations to ${outPath}`);
}
